apiVersion: apps/v1
kind: Deployment
metadata:
  name: gns3
  namespace: gns3
  labels:
    app: gns3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gns3
  template:
    metadata:
      labels:
        app: gns3
    spec:
      containers:
        - name: gns3
          image: misi0/gns3server:latest
          ports:
            - containerPort: 3080   # Puerto web de GNS3 Server
          env:
            - name: GNS3_SERVER_BIND_ADDRESS
              value: "0.0.0.0"
            # Puedes agregar más variables de entorno si necesitas
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gns3-service
  namespace: gns3
spec:
  selector:
    app: gns3
  ports:
    - protocol: TCP
      port: 3089
      targetPort: 3089
  type: ClusterIP
