
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gns3
  namespace: gns3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gns3
  template:
    metadata:
      labels:
        app: gns3
    spec:
      hostNetwork: true
      containers:
      - name: gns3
        image: pmietlicki/gns3-server:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        ports:
        - containerPort: 3080
        env:
        - name: GNS3_SERVER_BIND_ADDRESS
          value: "0.0.0.0"
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
